[package]
name = "yara-x-binja"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", branch = "dev" }
bstr = "1.11.1"
log = "0.4.22"
serde_json = "1.0.133"
yara-x = "0.11.1"
